---

- name: Create zookeeper directory if it does not exists
  become: true
  file:
    path: '/mnt/data/zookeeper/{{item.path}}'
    state: directory
  loop:
    - { path: 'data' }
    - { path: 'log' }
  when: (dojot_storage_class_name == "local-storage") and
        ('kafka_nodes' in {{ group_names }})

- name: Create zookeeper volume
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'zookeeper_data.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'zookeeper_log.yaml.j2') | from_yaml }}"
  when: (dojot_storage_class_name == "local-storage") and
        ('master_nodes' in {{ group_names }})