## This role is responsible for deploying verneMq for dojot

- name: dojot - x509 Identity Management Objects
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'x509_identity_mgmt_secrets.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'x509_identity_mgmt_deployment.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'x509_identity_mgmt_service.yaml.j2') | from_yaml }}"

- name: dojot - x509 Identity Management Persistent Volume Claim
  when: "{{ dojot_x509_identity_mgmt_persistent_volumes }}"
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'x509_identity_mgmt_pvc.yaml.j2') | from_yaml }}"
