---

- name: Create mongodb directory if it does not exists
  become: true
  file:
    path: /mnt/data/mongodb
    state: directory
  when: (dojot_storage_class_name == "local-storage") and
        ('dojot_nodes' in {{ group_names }})

- name: Create mongodb volume
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'mongo.yaml.j2') | from_yaml }}"
  when: (dojot_storage_class_name == "local-storage") and
        ('master_nodes' in {{ group_names }})